name: ea_kazi
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^4.2.1
  flutter_native_splash: ^2.2.6
  flutter_riverpod: ^2.0.0-dev.9
  flutter_svg: ^1.1.1+1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  video_player: ^2.4.6
  chewie: ^1.3.4
  json_annotation: ^4.4.0
  dio: ^4.0.6
  retrofit: '>=3.0.0 <4.0.0'
  injectable: ^1.5.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.1
  build_runner: ^2.2.0
  json_serializable: ^6.1.6
  retrofit_generator: '>=4.0.0 <5.0.0'
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/videos/

flutter_native_splash:
  image: assets/images/logo.png
  color: '##FFFFFF'
